// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/18/2025, 11:59:50 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/lobo/Desktop/Progress/Built in 2025/r1/sdk/creations-sdk/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lobo/Desktop/Progress/Built in 2025/r1/sdk/creations-sdk/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lobo/Desktop/Progress/Built in 2025/r1/sdk/creations-sdk/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lobo/Desktop/Progress/Built in 2025/r1/sdk/creations-sdk/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lobo/Desktop/Progress/Built in 2025/r1/sdk/creations-sdk/plugins/**/*.{js,ts,mjs}","/Users/lobo/Desktop/Progress/Built in 2025/r1/sdk/creations-sdk/composables/**/*.{js,ts,mjs}","/Users/lobo/Desktop/Progress/Built in 2025/r1/sdk/creations-sdk/utils/**/*.{js,ts,mjs}","/Users/lobo/Desktop/Progress/Built in 2025/r1/sdk/creations-sdk/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lobo/Desktop/Progress/Built in 2025/r1/sdk/creations-sdk/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/lobo/Desktop/Progress/Built in 2025/r1/sdk/creations-sdk/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/lobo/Desktop/Progress/Built in 2025/r1/sdk/creations-sdk/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["17"] = "/Users/lobo/Desktop/Progress/Built in 2025/r1/sdk/creations-sdk/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;